#!/bin/sh

name="rpi-man-get"
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bin_path="/usr/local/bin"

install()
{
    echo "Installing rpi-man..."
    install_dependencies
    echo "Make rpi-man-server as global command..."
    ln -s $path/bin/rpi-man-server $bin_path
    echo "rpi-man is now installed on your Raspberry PI."
    echo "Type 'sudo rpi-man-server start' to start."
}

install_dependencies()
{
    echo "Installing dependencies..."
    npm install
}

uninstall()
{
    if rpi-man-server status; then
        rpi-man-server stop
    fi
    echo "Uninstalling rpi-man..."
    echo "Removing rpi-man-server from global commands..."
    rm $bin_path/rpi-man-server
    echo "Now it is safe to remove rpi-man by delete this folder."
    echo "See you next time ;)"
}

upgrade()
{
    is_running=0
    if rpi-man-server status; then
        echo "$name detects that rpi-man-server is now running."
        is_running=1
        rpi-man-server stop
        echo "$name will restart rpi-man-server immediately after upgrade completes."
    fi
    echo "Upgrading rpi-man..."
    echo "Pulling the latest rpi-man from Github..."
    git pull origin master
    install_dependencies
    if [ $is_running = 1 ]; then
        rpi-man-server start
    fi
    echo "rpi-man is now up-to-date."
}






case $1 in
    install)
        install
        ;;
    uninstall)
        uninstall
        ;;
    upgrade)
        upgrade
        ;;
    *)
        echo "Usage: $name {install|uninstall|upgrade}"
        ;;
esac

exit 0
